export interface Paragraph {
  id:string,
  text:{
    text:any,
    size:any,
    align:any,
    color:any,
    lineHeight:any
  },
  style:{
    width:any,
    height:any,
    padding:any,
    margin:any,
    borderColor:any,
    borderThickness:any,
    overflow:any,
    class:any
  }
  script:any
}
